.TH ANALYSE-GAMMA 1 ANALYSE-GAMMA
.SH NAME
analyse-gamma - Gamma adjustment analysis tool
.SH SYNOPSIS
.BR analyse-gamma
.SH DESCRIPTION
Analyses the gamma ramps on your CRTC:s, and outputs the
results to stdout.
.SH RATIONALE
See <https://github.com/jonls/redshift/issues/117>.
.SH "SEE ALSO"
.BR crt-calibrator (1),
.BR xgamma (1),
.BR xrandr (1),
.BR redshift (1),
.BR blueshift (1)
.SH AUTHORS
Principal author, Mattias Andrée.  See the COPYING file for the full
list of authors.
.SH LICENSE
Copyright \(co 2014, 2015  Mattias Andrée
.br
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
.SH BUGS
Please report bugs to m@maandree.se
